version: 2
general:
  branches:
    ignore:
      - /binary-.*/

jobs:
  build:
    docker:
      - image: autozimu/languageclientneovim
    steps:
      - checkout
      - run: make ci

workflows:
  version: 2
  dev:
    jobs:
      - build

# vim: tabstop=2
