name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v10
    # - uses: mxschmitt/action-tmate@v3
    - run: nix-shell --run "rustup set profile default && make ci"
